
project_id = "kyxotvtinlpackztktxe"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[functions]
[functions.voice-to-text]
verify_jwt = false
[functions.save-transcription-correction]
verify_jwt = false
[functions.get-mapbox-token]
verify_jwt = false
[functions.save-mapbox-token]
verify_jwt = false

