// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyxotvtinlpackztktxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5eG90dnRpbmxwYWNrenRrdHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDgwMDksImV4cCI6MjA1NTk4NDAwOX0.6sz7X9I5vPxHZljpfXOpijjFO6rrfRVHrPGOvRTIRU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);